<?php

// app/Exports/CustomReportExport.php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class CustomReportExport implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'Custom Report';
    }

    public function headings(): array
    {
        return [
            'Incident ID', 'Title', 'Category', 'Department', 'Status',
            'Priority', 'Severity', 'Reported By', 'Assigned To',
            'Location', 'Created At', 'Resolved At',
        ];
    }

    public function array(): array
    {
        $rows = [
            ['Report Period', ($this->data['date_from'] ?? '').' to '.($this->data['date_to'] ?? '')],
            ['Generated At', $this->data['generated_at'] ?? ''],
            ['Generated By', $this->data['generated_by'] ?? ''],
            ['Total Incidents', $this->data['total'] ?? 0],
            [''],
        ];

        foreach ($this->data['incidents'] as $incident) {
            $rows[] = [
                $incident->incident_id,
                $incident->title,
                $incident->category?->name ?? 'N/A',
                $incident->department?->name ?? 'N/A',
                ucfirst(str_replace('_', ' ', $incident->status)),
                ucfirst($incident->priority),
                ucfirst($incident->severity),
                $incident->is_anonymous ? 'Anonymous' : ($incident->reporter?->name ?? 'N/A'),
                $incident->assignedTo?->name ?? 'Unassigned',
                $incident->location ?? 'N/A',
                $incident->created_at->format('d M Y, H:i'),
                $incident->resolved_at?->format('d M Y, H:i') ?? 'N/A',
            ];
        }

        return $rows;
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true, 'size' => 13]],
            6 => [
                'font' => ['bold' => true],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '2563EB']],
                'font' => ['color' => ['rgb' => 'FFFFFF']],
            ],
        ];
    }
}
