<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMultipleSheets;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class DepartmentReportExport implements WithMultipleSheets
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function sheets(): array
    {
        $sheets = [];

        if (isset($this->data['department'])) {
            // Single department export
            $sheets[] = new DepartmentDetailSheet($this->data);
            $sheets[] = new DepartmentIncidentsSheet($this->data);
            $sheets[] = new DepartmentUsersSheet($this->data);
        } else {
            // All departments overview
            $sheets[] = new DepartmentOverviewSheet($this->data);
        }

        return $sheets;
    }
}

class DepartmentOverviewSheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'Department Overview';
    }

    public function headings(): array
    {
        return [
            'Department', 'Code', 'Total Incidents', 'Active', 'Resolved',
            'Escalated', 'SLA Compliance %', 'Avg Response (min)', 'Performance %',
        ];
    }

    public function array(): array
    {
        $rows = [
            ['Report Period', $this->data['period'] ?? 'N/A'],
            ['Generated At', $this->data['generated_at'] ?? ''],
            ['Generated By', $this->data['generated_by'] ?? ''],
            [''],
        ];

        $stats = $this->data['stats'] ?? [];
        foreach ($stats as $dept) {
            $rows[] = [
                $dept['name'] ?? '',
                $dept['code'] ?? '',
                $dept['total'] ?? 0,
                $dept['active'] ?? 0,
                $dept['resolved'] ?? 0,
                $dept['escalated'] ?? 0,
                $dept['sla_compliance'] ?? 0,
                $dept['avg_response_time'] ?? 0,
                $dept['performance'] ?? 0,
            ];
        }

        return $rows;
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true, 'size' => 13]],
            4 => ['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '2563EB']], 'font' => ['color' => ['rgb' => 'FFFFFF']]],
        ];
    }
}

class DepartmentDetailSheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'KPI Summary';
    }

    public function headings(): array
    {
        return ['Metric', 'Value'];
    }

    public function array(): array
    {
        $dept = $this->data['department'] ?? null;
        $kpi = $this->data['kpi'] ?? [];

        return [
            ['Department', $dept->name ?? 'N/A'],
            ['Code', $dept->code ?? 'N/A'],
            ['Report Period', $this->data['period'] ?? 'N/A'],
            ['Generated At', $this->data['generated_at'] ?? ''],
            [''],
            ['Total Incidents', $kpi['total_incidents'] ?? 0],
            ['Open Incidents', $kpi['open_incidents'] ?? 0],
            ['Resolved Incidents', $kpi['resolved_incidents'] ?? 0],
            ['Closed Incidents', $kpi['closed_incidents'] ?? 0],
            ['Escalated Incidents', $kpi['escalated_incidents'] ?? 0],
            ['SLA Breaches', $kpi['sla_breaches'] ?? 0],
            ['SLA Compliance', ($kpi['sla_compliance'] ?? 0).'%'],
            ['Resolution Rate', ($kpi['resolution_rate'] ?? 0).'%'],
            ['Avg Response Time', ($kpi['avg_response_time'] ?? 0).' min'],
            ['Avg Resolution Time', ($kpi['avg_resolution_time'] ?? 0).' min'],
        ];
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true, 'size' => 13]],
            6 => ['font' => ['bold' => true]],
        ];
    }
}

class DepartmentIncidentsSheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'Incidents';
    }

    public function headings(): array
    {
        return ['Incident ID', 'Title', 'Category', 'Status', 'Priority', 'Severity', 'Reported By', 'Assigned To', 'Created At'];
    }

    public function array(): array
    {
        $incidents = $this->data['incidents'] ?? [];

        return $incidents->map(function ($incident) {
            return [
                $incident->incident_id,
                $incident->title,
                $incident->category?->name ?? 'N/A',
                ucfirst(str_replace('_', ' ', $incident->status)),
                ucfirst($incident->priority),
                ucfirst($incident->severity),
                $incident->is_anonymous ? 'Anonymous' : ($incident->reporter?->name ?? 'N/A'),
                $incident->assignedTo?->name ?? 'Unassigned',
                $incident->created_at->format('d M Y, H:i'),
            ];
        })->toArray();
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'E5E7EB']]],
        ];
    }
}

class DepartmentUsersSheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'Users';
    }

    public function headings(): array
    {
        return ['Name', 'Email', 'Employee ID', 'Designation', 'Role', 'Status'];
    }

    public function array(): array
    {
        $users = $this->data['users'] ?? [];

        return $users->map(function ($user) {
            return [
                $user->name,
                $user->email,
                $user->employee_id ?? 'N/A',
                $user->designation ?? 'N/A',
                $user->getFirstRoleName(),
                ucfirst($user->status),
            ];
        })->toArray();
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'E5E7EB']]],
        ];
    }
}
