<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMultipleSheets;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class KpiReportExport implements WithMultipleSheets
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function sheets(): array
    {
        return [
            'KPI Summary' => new KpiSummarySheet($this->data),
            'Department Performance' => new DepartmentPerformanceSheet($this->data),
            'Category Breakdown' => new CategoryBreakdownSheet($this->data),
            'SLA Compliance' => new SlaComplianceSheet($this->data),
        ];
    }
}

class KpiSummarySheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'KPI Summary';
    }

    public function headings(): array
    {
        return ['Metric', 'Value'];
    }

    public function array(): array
    {
        $kpi = $this->data['kpi'] ?? [];

        return [
            ['Report Period', ($this->data['date_from'] ?? '').' to '.($this->data['date_to'] ?? '')],
            ['Generated At', $this->data['generated_at'] ?? ''],
            ['Generated By', $this->data['generated_by'] ?? ''],
            [''],
            ['Total Incidents', $kpi['total_incidents'] ?? 0],
            ['Open Incidents', $kpi['open_incidents'] ?? 0],
            ['In Progress', $kpi['in_progress_incidents'] ?? 0],
            ['Resolved', $kpi['resolved_incidents'] ?? 0],
            ['Closed', $kpi['closed_incidents'] ?? 0],
            ['Escalated', $kpi['escalated_incidents'] ?? 0],
            ['Rejected', $kpi['rejected_incidents'] ?? 0],
            ['SLA Breaches', $kpi['sla_breaches'] ?? 0],
            ['SLA Compliance', ($kpi['sla_compliance'] ?? 0).'%'],
            ['Resolution Rate', ($kpi['resolution_rate'] ?? 0).'%'],
            ['Avg Response Time', ($kpi['avg_response_time'] ?? 0).' min'],
            ['Avg Resolution Time', ($kpi['avg_resolution_time'] ?? 0).' min'],
        ];
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true, 'size' => 14]],
            5 => ['font' => ['bold' => true]],
        ];
    }
}

class DepartmentPerformanceSheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'Department Performance';
    }

    public function headings(): array
    {
        return ['Department', 'Total', 'Active', 'Resolved', 'Escalated', 'SLA %', 'Avg Response (min)', 'Performance %'];
    }

    public function array(): array
    {
        return array_map(function ($dept) {
            return [
                $dept['name'] ?? '',
                $dept['total'] ?? 0,
                $dept['active'] ?? 0,
                $dept['resolved'] ?? 0,
                $dept['escalated'] ?? 0,
                $dept['sla_compliance'] ?? 0,
                $dept['avg_response_time'] ?? 0,
                $dept['performance'] ?? 0,
            ];
        }, $this->data['department_performance'] ?? []);
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'E5E7EB']]],
        ];
    }
}

class CategoryBreakdownSheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'Category Breakdown';
    }

    public function headings(): array
    {
        return ['Category', 'Total', 'Open', 'Resolved', 'SLA %'];
    }

    public function array(): array
    {
        return array_map(function ($cat) {
            return [
                $cat['name'] ?? '',
                $cat['total'] ?? 0,
                $cat['open'] ?? 0,
                $cat['resolved'] ?? 0,
                $cat['sla_compliance'] ?? 0,
            ];
        }, $this->data['category_breakdown'] ?? []);
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'E5E7EB']]],
        ];
    }
}

class SlaComplianceSheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'SLA Compliance';
    }

    public function headings(): array
    {
        return ['Department', 'SLA Compliance %'];
    }

    public function array(): array
    {
        return array_map(function ($value, $key) {
            return [$key, $value];
        }, $this->data['sla_compliance'] ?? [], array_keys($this->data['sla_compliance'] ?? []));
    }

    public function styles(Worksheet $sheet)
    {
        return [
            1 => ['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'E5E7EB']]],
        ];
    }
}
