<?php

// app/Exports/SlaReportExport.php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMultipleSheets;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class SlaReportExport implements WithMultipleSheets
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function sheets(): array
    {
        return [
            'SLA Summary' => new SlaSummarySheet($this->data),
            'SLA by Department' => new SlaByDepartmentSheet($this->data),
            'SLA Breaches' => new SlaBreachesSheet($this->data),
        ];
    }
}

class SlaSummarySheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'SLA Summary';
    }

    public function headings(): array
    {
        return ['Metric', 'Value'];
    }

    public function array(): array
    {
        return [
            ['Report Period', ($this->data['date_from'] ?? '').' to '.($this->data['date_to'] ?? '')],
            ['Generated At', $this->data['generated_at'] ?? ''],
            ['Generated By', $this->data['generated_by'] ?? ''],
            [''],
            ['Overall SLA Compliance', ($this->data['overall_sla'] ?? 0).'%'],
        ];
    }

    public function styles(Worksheet $sheet)
    {
        return [1 => ['font' => ['bold' => true, 'size' => 13]]];
    }
}

class SlaByDepartmentSheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'SLA by Department';
    }

    public function headings(): array
    {
        return ['Department', 'SLA Compliance %'];
    }

    public function array(): array
    {
        return array_map(fn ($key, $value) => [$key, $value], array_keys($this->data['sla_by_department'] ?? []), $this->data['sla_by_department'] ?? []);
    }

    public function styles(Worksheet $sheet)
    {
        return [1 => ['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'E5E7EB']]]];
    }
}

class SlaBreachesSheet implements FromArray, ShouldAutoSize, WithHeadings, WithStyles, WithTitle
{
    protected array $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function title(): string
    {
        return 'SLA Breaches';
    }

    public function headings(): array
    {
        return ['Incident ID', 'Title', 'Department', 'Category', 'Breach Count', 'SLA Due', 'Status'];
    }

    public function array(): array
    {
        return ($this->data['sla_breaches'] ?? [])->map(fn ($b) => [
            $b->incident_id, $b->title, $b->department?->name, $b->category?->name,
            $b->sla_breach_count, $b->sla_due_at?->format('Y-m-d H:i'), ucfirst(str_replace('_', ' ', $b->status)),
        ])->toArray();
    }

    public function styles(Worksheet $sheet)
    {
        return [1 => ['font' => ['bold' => true], 'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'E5E7EB']]]];
    }
}
