{{-- resources/views/reports/exports/category-pdf.blade.php --}}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Category Analysis Report - IRMSystem</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 10px;
            line-height: 1.4;
            color: #333;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1a56db;
            padding-bottom: 15px;
        }

        .header h1 {
            font-size: 20px;
            color: #1a56db;
            margin: 0 0 5px;
        }

        .header .subtitle {
            font-size: 11px;
            color: #666;
        }

        .meta-info {
            margin-bottom: 20px;
            font-size: 10px;
            color: #666;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 10px;
        }

        table.data-table th {
            background: #1a56db;
            color: white;
            padding: 8px 6px;
            text-align: left;
            font-weight: bold;
        }

        table.data-table td {
            padding: 6px;
            border-bottom: 1px solid #e5e7eb;
        }

        table.data-table tr:nth-child(even) {
            background: #f9fafb;
        }

        .footer {
            text-align: center;
            font-size: 9px;
            color: #999;
            margin-top: 30px;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Category Analysis Report</h1>
        <div class="subtitle">Incident Reporting & Management System</div>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td style="font-weight:bold;width:100px;">Period:</td>
                <td>{{ $period ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">Generated:</td>
                <td>{{ $generated_at ?? now()->format('d M Y, H:i') }}</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">By:</td>
                <td>{{ $generated_by ?? 'System' }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th>Category</th>
                <th>Total</th>
                <th>Resolved</th>
                <th>Open</th>
                <th>Escalated</th>
                <th>SLA Breaches</th>
                <th>SLA %</th>
                <th>Resolution %</th>
            </tr>
        </thead>
        <tbody>
            @forelse($categories ?? [] as $cat)
            <tr>
                <td>{{ $cat['name'] ?? '' }}</td>
                <td>{{ $cat['total'] ?? 0 }}</td>
                <td>{{ $cat['resolved'] ?? 0 }}</td>
                <td>{{ $cat['open'] ?? 0 }}</td>
                <td>{{ $cat['escalated'] ?? 0 }}</td>
                <td>{{ $cat['breached'] ?? 0 }}</td>
                <td>{{ $cat['sla_compliance'] ?? 0 }}%</td>
                <td>{{ $cat['resolution_rate'] ?? 0 }}%</td>
            </tr>
            @empty
            <tr>
                <td colspan="8" style="text-align:center;">No category data available</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by IRMSystem - Incident Reporting & Management System</p>
        <p>© {{ date('Y') }} IRMSystem. All rights reserved.</p>
    </div>
</body>

</html>