{{-- resources/views/reports/exports/custom-pdf.blade.php --}}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Custom Report - IRMSystem</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 9px;
            line-height: 1.4;
            color: #333;
            padding: 15px;
        }

        .header {
            text-align: center;
            margin-bottom: 15px;
            border-bottom: 2px solid #1a56db;
            padding-bottom: 10px;
        }

        .header h1 {
            font-size: 18px;
            color: #1a56db;
            margin: 0 0 3px;
        }

        .header .subtitle {
            font-size: 10px;
            color: #666;
        }

        .meta-info {
            margin-bottom: 15px;
            font-size: 9px;
            color: #666;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 8px;
        }

        table.data-table th {
            background: #1a56db;
            color: white;
            padding: 6px 4px;
            text-align: left;
            font-weight: bold;
        }

        table.data-table td {
            padding: 4px;
            border-bottom: 1px solid #e5e7eb;
        }

        table.data-table tr:nth-child(even) {
            background: #f9fafb;
        }

        .footer {
            text-align: center;
            font-size: 8px;
            color: #999;
            margin-top: 20px;
            border-top: 1px solid #e5e7eb;
            padding-top: 8px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Custom Date Range Report</h1>
        <div class="subtitle">Incident Reporting & Management System</div>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td style="font-weight:bold;width:80px;">Period:</td>
                <td>{{ $date_from ?? '' }} to {{ $date_to ?? '' }}</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">Total:</td>
                <td>{{ $total ?? 0 }} incidents</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">Generated:</td>
                <td>{{ $generated_at ?? now()->format('d M Y, H:i') }}</td>
            </tr>
            <tr>
                <td style="font-weight:bold;">By:</td>
                <td>{{ $generated_by ?? 'System' }}</td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Category</th>
                <th>Department</th>
                <th>Status</th>
                <th>Priority</th>
                <th>Reported By</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($incidents ?? [] as $incident)
            <tr>
                <td>{{ $incident->incident_id }}</td>
                <td>{{ Str::limit($incident->title, 50) }}</td>
                <td>{{ $incident->category?->name ?? 'N/A' }}</td>
                <td>{{ $incident->department?->name ?? 'N/A' }}</td>
                <td>{{ str_replace('_', ' ', ucfirst($incident->status)) }}</td>
                <td>{{ ucfirst($incident->priority) }}</td>
                <td>{{ $incident->is_anonymous ? 'Anonymous' : ($incident->reporter?->name ?? 'N/A') }}</td>
                <td>{{ $incident->created_at->format('d M Y') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="8" style="text-align:center;">No incidents found</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by IRMSystem - Incident Reporting & Management System</p>
        <p>© {{ date('Y') }} IRMSystem. All rights reserved.</p>
    </div>
</body>

</html>