{{-- resources/views/reports/exports/department-pdf.blade.php --}}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Department Report - IRMSystem</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 11px;
            line-height: 1.4;
            color: #333;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1a56db;
            padding-bottom: 15px;
        }

        .header h1 {
            font-size: 20px;
            color: #1a56db;
            margin: 0 0 5px;
        }

        .header .subtitle {
            font-size: 11px;
            color: #666;
        }

        .meta-info {
            margin-bottom: 20px;
            font-size: 10px;
            color: #666;
        }

        .meta-info table {
            width: 100%;
            border-collapse: collapse;
        }

        .meta-info td {
            padding: 3px 8px;
        }

        .meta-info .label {
            font-weight: bold;
            width: 120px;
        }

        .section-title {
            font-size: 14px;
            font-weight: bold;
            color: #1a56db;
            margin: 20px 0 10px;
            padding-bottom: 5px;
            border-bottom: 1px solid #e5e7eb;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            font-size: 10px;
        }

        table.data-table th {
            background: #1a56db;
            color: white;
            padding: 8px 6px;
            text-align: left;
            font-weight: bold;
        }

        table.data-table td {
            padding: 6px;
            border-bottom: 1px solid #e5e7eb;
        }

        table.data-table tr:nth-child(even) {
            background: #f9fafb;
        }

        .kpi-grid {
            display: table;
            width: 100%;
            margin-bottom: 15px;
        }

        .kpi-row {
            display: table-row;
        }

        .kpi-cell {
            display: table-cell;
            width: 16.6%;
            text-align: center;
            padding: 10px 5px;
            border: 1px solid #e5e7eb;
        }

        .kpi-value {
            font-size: 18px;
            font-weight: bold;
        }

        .kpi-label {
            font-size: 8px;
            color: #666;
            text-transform: uppercase;
        }

        .footer {
            text-align: center;
            font-size: 9px;
            color: #999;
            margin-top: 30px;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }

        .status-badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
        }

        .status-open {
            background: #dbeafe;
            color: #1e40af;
        }

        .status-acknowledged {
            background: #fef3c7;
            color: #92400e;
        }

        .status-in_progress {
            background: #ede9fe;
            color: #5b21b6;
        }

        .status-escalated {
            background: #fce7f3;
            color: #9b1c1c;
        }

        .status-resolved {
            background: #d1fae5;
            color: #065f46;
        }

        .status-closed {
            background: #e2e8f0;
            color: #475569;
        }

        .status-rejected {
            background: #fee2e2;
            color: #991b1b;
        }
    </style>
</head>

<body>

    @if(isset($department))
    {{-- Single Department Report --}}
    <div class="header">
        <h1>{{ $department->name }} - Department Report</h1>
        <div class="subtitle">Incident Reporting & Management System</div>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td class="label">Department:</td>
                <td>{{ $department->name }} ({{ $department->code }})</td>
            </tr>
            <tr>
                <td class="label">Report Period:</td>
                <td>{{ $period ?? 'N/A' }}</td>
            </tr>
            @if(!empty($filters))
            <tr>
                <td class="label">Filters:</td>
                <td>
                    @if($filters['status']) Status: {{ $filters['status'] }} | @endif
                    @if($filters['severity']) Severity: {{ $filters['severity'] }} | @endif
                    @if($filters['search']) Search: {{ $filters['search'] }} | @endif
                </td>
            </tr>
            @endif
            <tr>
                <td class="label">Generated:</td>
                <td>{{ $generated_at ?? now()->format('d M Y, H:i') }}</td>
            </tr>
            <tr>
                <td class="label">Generated By:</td>
                <td>{{ $generated_by ?? 'System' }}</td>
            </tr>
        </table>
    </div>

    {{-- KPI Summary --}}
    <div class="section-title">KPI Summary</div>
    <div class="kpi-grid">
        @php $kpi = $kpi ?? []; @endphp
        <div class="kpi-row">
            <div class="kpi-cell">
                <div class="kpi-value" style="color:#3b82f6;">{{ $kpi['total_incidents'] ?? 0 }}</div>
                <div class="kpi-label">Total</div>
            </div>
            <div class="kpi-cell">
                <div class="kpi-value" style="color:#f59e0b;">{{ $kpi['open_incidents'] ?? 0 }}</div>
                <div class="kpi-label">Open</div>
            </div>
            <div class="kpi-cell">
                <div class="kpi-value" style="color:#10b981;">{{ $kpi['resolved_incidents'] ?? 0 }}</div>
                <div class="kpi-label">Resolved</div>
            </div>
            <div class="kpi-cell">
                <div class="kpi-value" style="color:#ef4444;">{{ $kpi['escalated_incidents'] ?? 0 }}</div>
                <div class="kpi-label">Escalated</div>
            </div>
            <div class="kpi-cell">
                <div class="kpi-value" style="color:#06b6d4;">{{ round($kpi['avg_response_time'] ?? 0, 1) }}m</div>
                <div class="kpi-label">Avg Response</div>
            </div>
            <div class="kpi-cell">
                <div class="kpi-value"
                    style="color:{{ ($kpi['sla_compliance'] ?? 100) >= 80 ? '#10b981' : '#f59e0b' }};">{{
                    $kpi['sla_compliance'] ?? 100 }}%</div>
                <div class="kpi-label">SLA</div>
            </div>
        </div>
    </div>

    {{-- Team Members --}}
    <div class="section-title">Team Members ({{ ($users ?? collect())->count() }})</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Employee ID</th>
                <th>Designation</th>
                <th>Role</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users ?? [] as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->employee_id ?? 'N/A' }}</td>
                <td>{{ $user->designation ?? 'N/A' }}</td>
                <td>{{ $user->getFirstRoleName() }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="5" style="text-align:center;">No users</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    {{-- Incidents --}}
    <div class="section-title">Incidents ({{ ($incidents ?? collect())->count() }})</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Category</th>
                <th>Status</th>
                <th>Priority</th>
                <th>Reported By</th>
                <th>Assigned To</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($incidents ?? [] as $incident)
            <tr>
                <td>{{ $incident->incident_id }}</td>
                <td>{{ Str::limit($incident->title, 50) }}</td>
                <td>{{ $incident->category?->name ?? 'N/A' }}</td>
                <td><span class="status-badge status-{{ str_replace('_', '-', $incident->status) }}">{{ str_replace('_',
                        ' ', ucfirst($incident->status)) }}</span></td>
                <td>{{ ucfirst($incident->priority) }}</td>
                <td>{{ $incident->is_anonymous ? 'Anonymous' : ($incident->reporter?->name ?? 'N/A') }}</td>
                <td>{{ $incident->assignedTo?->name ?? 'Unassigned' }}</td>
                <td>{{ $incident->created_at->format('d M Y') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="8" style="text-align:center;">No incidents found</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    @else
    {{-- All Departments Overview --}}
    <div class="header">
        <h1>All Departments Performance Report</h1>
        <div class="subtitle">Incident Reporting & Management System</div>
    </div>

    <div class="meta-info">
        <table>
            <tr>
                <td class="label">Report Period:</td>
                <td>{{ $period ?? 'N/A' }}</td>
            </tr>
            <tr>
                <td class="label">Generated:</td>
                <td>{{ $generated_at ?? now()->format('d M Y, H:i') }}</td>
            </tr>
            <tr>
                <td class="label">Generated By:</td>
                <td>{{ $generated_by ?? 'System' }}</td>
            </tr>
        </table>
    </div>

    <div class="section-title">Department Performance</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Department</th>
                <th>Code</th>
                <th>Total</th>
                <th>Active</th>
                <th>Resolved</th>
                <th>Escalated</th>
                <th>SLA %</th>
                <th>Avg Response</th>
                <th>Performance</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stats ?? [] as $dept)
            <tr>
                <td>{{ $dept['name'] ?? '' }}</td>
                <td>{{ $dept['code'] ?? '' }}</td>
                <td>{{ $dept['total'] ?? 0 }}</td>
                <td>{{ $dept['active'] ?? 0 }}</td>
                <td>{{ $dept['resolved'] ?? 0 }}</td>
                <td>{{ $dept['escalated'] ?? 0 }}</td>
                <td>{{ $dept['sla_compliance'] ?? 0 }}%</td>
                <td>{{ $dept['avg_response_time'] ?? 0 }} min</td>
                <td>{{ $dept['performance'] ?? 0 }}%</td>
            </tr>
            @empty
            <tr>
                <td colspan="9" style="text-align:center;">No data</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>Generated by IRMSystem - Incident Reporting & Management System</p>
        <p>© {{ date('Y') }} IRMSystem. All rights reserved. This is a computer-generated report.</p>
    </div>
</body>

</html>